### ISSUE TITLE
Добавить символ валюты теньге  - ₸  вместо KZT 

### ISSUE THREAD

**Issue by badigit** [ardov/zerro#109]
Дает более ровное отображение списка операций, когда код валюты занимает один символ( ₸ ) , а не три (KZT)
Код символа U+20B8
![image](https://user-images.githubusercontent.com/33813448/211017626-121054cf-9a95-43de-9f00-54ee6ce98f4c.png)

**Comment by ardov** [comment]
Добавил символ в бете, спасибо! Почему-то не нашёл его, когда изначально добавлял символы)
Но проблема с выравниванием всё равно останется, не у всех валют есть символы. Но в этом месте, кажется, лаконичные символы лучше)
