### ISSUE TITLE
Budget drawer

### ISSUE THREAD

**Issue by dhvcc** [ardov/zerro#46]
Скорее неудобство, чем проблема

С мобильной версии открываю окно с подробной инфой про категорию бюджета
У меня довольно большой экран, поэтому, что бы закрыть окно я не буду тянуться в самый верх экрана и нажимать крестик
По логике просто нажимаю кнопку назад (тк в мобильной версии окно во весь экран, предполагая, что это считается как отдельный роут)
Но вместо закрытия окна тебя перекидывает на прошедшую страницу по истории

Думаю, можно было бы добавить окно с подробностями как отдельный путь

**Comment by ardov** [comment]
Да, согласен, есть в планах это сделать 👍
